routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix'=>'admin','middleware'=>'auth.checkrole','as'=>'admin.'],function (){

    Route::get('categories',['as'=>'categories.index','uses'=>'CategoriesController@index']);
    Route::get('categories/create',['as'=>'categories.create','uses'=>'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=>'categories.edit','uses'=>'CategoriesController@edit']);
    Route::post('categories/update/{id}',['as'=>'categories.update','uses'=>'CategoriesController@update']);
    Route::post('categories/store',['as'=>'categories.store','uses'=>'CategoriesController@store']);
    Route::get('categories/destroy/{id}',['as'=>'categories.destroy','uses'=>'CategoriesController@destroy']);

    Route::get('clients',['as'=>'clients.index','uses'=>'ClientsController@index']);
    Route::get('clients/create',['as'=>'clients.create','uses'=>'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=>'clients.edit','uses'=>'ClientsController@edit']);
    Route::post('clients/update/{id}',['as'=>'clients.update','uses'=>'ClientsController@update']);
    Route::post('clients/store',['as'=>'clients.store','uses'=>'ClientsController@store']);
    Route::get('clients/destroy/{id}',['as'=>'clients.destroy','uses'=>'ClientsController@destroy']);


    Route::get('products',['as'=>'products.index','uses'=>'ProductsController@index']);
    Route::get('products/create',['as'=>'products.create','uses'=>'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=>'products.edit','uses'=>'ProductsController@edit']);
    Route::post('products/update/{id}',['as'=>'products.update','uses'=>'ProductsController@update']);
    Route::post('products/store',['as'=>'products.store','uses'=>'ProductsController@store']);
    Route::get('products/destroy/{id}',['as'=>'products.destroy','uses'=>'ProductsController@destroy']);

    Route::get('orders',['as'=>'orders.index','uses'=>'OrdersController@index']);
    Route::get('orders/edit/{id}',['as'=>'orders.edit','uses'=>'OrdersController@edit']);
    Route::post('orders/update/{id}',['as'=>'orders.update','uses'=>'OrdersController@update']);

    Route::get('cupoms',['as'=>'cupoms.index','uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create','uses'=>'CupomsController@create']);
    Route::post('cupoms/store',['as'=>'cupoms.store','uses'=>'CupomsController@store']);
    Route::get('cupoms/edit/{id}',['as'=>'cupoms.edit','uses'=>'OrdersController@edit']);
    Route::get('cupoms/destroy/{id}',['as'=>'cupoms.destroy','uses'=>'CupomsController@destroy']);
});

    Route::group(['prefix'=>'customer', 'as'=>'customer.'],function (){
    Route::get('order/create',['as'=>'order.create','uses'=>'CheckoutController@create']);
    Route::post('order/store',['as'=>'order.store','uses'=>'CheckoutController@store']);
    Route::get('order',['as'=>'order.index','uses'=>'CheckoutController@index']);




    });

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\AdminClientRequest;


use App\Repositories\ClientRepository;
use App\Services\ClientService;

/**
 * Class ClientsController.
 *
 * @package namespace App\Http\Controllers;
 */
class ClientsController extends Controller
{
    private $repository;
    /**
     * @var ClientService
     */
    private $service;
    /**
     * @var ClientService
     */
    private $clientService;
    public function __construct(ClientRepository $repository, ClientService $clientService)
    {
        $this->repository = $repository;
        $this->clientService = $clientService;
    }
    public function index(){
        $clients = $this->repository->paginate(10);
        return view('admin.clients.index', compact('clients'));
    }
    public function create(){
        return view('admin.clients.create');
    }
    public function store(AdminClientRequest $request){
        $data = $request->all();
        $this->clientService->create($data);
        //dd($request->all());
        return redirect()->route('admin.clients.index');
    }
    public function edit($id){
        $clients = $this->repository->find($id);
        return view('admin.clients.edit',compact('clients'));
    }
    public function update(AdminClientRequest $request, $id){
        $data = $request->all();
        $this->clientService->update($data, $id);
        return redirect()->route('admin.clients.index');

    }
    public function destroy($id){
        $this->repository->delete($id);
        return redirect()->route('admin.clients.index');
    }
}

resources/views/admin/clients/_form.blade.php
<div class="form-group">

    {!! Form::label('Name','Nome:')!!}
    {!! Form::text('user[name]',null,['class'=>'form-control'])!!}
</div>

<div class="form-group">
    {!! Form::label('E-mail', 'E-mail:') !!}
    {!! Form::text('user[email]',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Telefone', 'Telefone:') !!}
    {!! Form::text('phone',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Endereço', 'Endereço:') !!}
    {!! Form::text('address',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Cidade', 'Cidade:') !!}
    {!! Form::text('city',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Estado', 'Estado:') !!}
    {!! Form::text('state',null,['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Cep', 'Cep:') !!}
    {!! Form::text('zipcode',null,['class'=>'form-control']) !!}
</div>

resources/views/admin/clients/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Nova cliente </h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.clients.store', 'class'=>'form']) !!}
        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Cadastrar novo',['class'=>'btn btn-primary'])!!}
        </div>

        {!! Form::close() !!}


    </div>

@endsection

resources/views/admin/clients/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Editando Cliente: {{ $clients->user->name }}</h3>

        @include('errors._check')

        {!! Form::model($clients,['route' => ['admin.clients.update', $clients->id] ]) !!}

        @include('admin.clients._form')

        <div class="form-group">
            {!! Form::submit('Salvar Usuário',['class' => 'btn btn-primary']) !!}
        </div>
        {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/clients/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Clientes</h3>
        <br>
        <a href="{{route('admin.clients.create')}}" class="btn btn-default">Novo cliente</a>
        <br>
        <br>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($clients as $client)
                <tr>
                    <td>{{$client->id}}</td>
                    <td>{{$client->user->name}}</td>
                    <td>
                        <a href="{{route('admin.clients.edit',['id'=>$client->id])}}" class="btn btn-default btn-sm">
                            Editar
                        </a>
                        <a href="{{route('admin.clients.destroy',['id'=>$client->id])}}" class="btn btn-danger btn-sm">
                            Remover
                        </a>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $clients->render() !!}
    </div>

@endsection