routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix'=>'admin','middleware'=>'auth.checkrole','as'=>'admin.'],function (){

    Route::get('categories',['as'=>'categories.index','uses'=>'CategoriesController@index']);
    Route::get('categories/create',['as'=>'categories.create','uses'=>'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=>'categories.edit','uses'=>'CategoriesController@edit']);
    Route::post('categories/update/{id}',['as'=>'categories.update','uses'=>'CategoriesController@update']);
    Route::post('categories/store',['as'=>'categories.store','uses'=>'CategoriesController@store']);
    Route::get('categories/destroy/{id}',['as'=>'categories.destroy','uses'=>'CategoriesController@destroy']);

    Route::get('clients',['as'=>'clients.index','uses'=>'ClientsController@index']);
    Route::get('clients/create',['as'=>'clients.create','uses'=>'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=>'clients.edit','uses'=>'ClientsController@edit']);
    Route::post('clients/update/{id}',['as'=>'clients.update','uses'=>'ClientsController@update']);
    Route::post('clients/store',['as'=>'clients.store','uses'=>'ClientsController@store']);
    Route::get('clients/destroy/{id}',['as'=>'clients.destroy','uses'=>'ClientsController@destroy']);


    Route::get('products',['as'=>'products.index','uses'=>'ProductsController@index']);
    Route::get('products/create',['as'=>'products.create','uses'=>'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=>'products.edit','uses'=>'ProductsController@edit']);
    Route::post('products/update/{id}',['as'=>'products.update','uses'=>'ProductsController@update']);
    Route::post('products/store',['as'=>'products.store','uses'=>'ProductsController@store']);
    Route::get('products/destroy/{id}',['as'=>'products.destroy','uses'=>'ProductsController@destroy']);

    Route::get('orders',['as'=>'orders.index','uses'=>'OrdersController@index']);
    Route::get('orders/edit/{id}',['as'=>'orders.edit','uses'=>'OrdersController@edit']);
    Route::post('orders/update/{id}',['as'=>'orders.update','uses'=>'OrdersController@update']);

    Route::get('cupoms',['as'=>'cupoms.index','uses'=>'CupomsController@index']);
    Route::get('cupoms/create',['as'=>'cupoms.create','uses'=>'CupomsController@create']);
    Route::post('cupoms/store',['as'=>'cupoms.store','uses'=>'CupomsController@store']);
    Route::get('cupoms/edit/{id}',['as'=>'cupoms.edit','uses'=>'OrdersController@edit']);
    Route::get('cupoms/destroy/{id}',['as'=>'cupoms.destroy','uses'=>'CupomsController@destroy']);
});

    Route::group(['prefix'=>'customer', 'as'=>'customer.'],function (){
    Route::get('order/create',['as'=>'order.create','uses'=>'CheckoutController@create']);
    Route::post('order/store',['as'=>'order.store','uses'=>'CheckoutController@store']);
    Route::get('order',['as'=>'order.index','uses'=>'CheckoutController@index']);




    });

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;



use App\Http\Requests\AdminCategoryRequest;
use App\Repositories\CategoryRepository;


/**
 * Class CategoriesController.
 *
 * @package namespace App\Http\Controllers;
 */
class CategoriesController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $repository;

    public function __construct(CategoryRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index(){
        $categories = $this->repository->paginate(5);

        return view('admin.categories.index', compact('categories'));
    }

    public function create(){
        return view('admin.categories.create');
    }

    public function store(AdminCategoryRequest $request){
        $data= $request->all();
        $this->repository->create($data);

        return redirect()->route('admin.categories.index')->with('message', 'Categoria Cadastrada com sucesso!');
    }

    public function edit($id){
        $category = $this->repository->find($id);
        return view('admin.categories.edit', compact('category'));



    }


    /**
     * @param AdminCategoryRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update( AdminCategoryRequest $request, $id)
    {
        $data= $request->all();
        $this->repository->update($data, $id);

        return redirect()->route('admin.categories.index')->with('message', 'Categoria editada com sucesso!');

    }
    public function destroy($id){
        $this->repository->delete($id);
        return redirect()->route('admin.categories.index')->with('message', 'Categoria removida com sucesso!');
    }
}

resources/views/admin/categories/_form.blade.php
<div class="form-group">
    {!! Form::label('Name','Nome:')!!}
    {!! Form::text('name',null,['class'=>'form-control'])!!}
</div>

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Nova categoria </h3>

        @include('errors._check')

        {!! Form::open(['route'=>'admin.categories.store', 'class'=>'form']) !!}
          @include('admin.categories._form')

        <div class="form-group">
            {!! Form::submit('Criar categoria',['class'=>'btn btn-primary'])!!}
        </div>

        {!! Form::close() !!}


    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
            <h3>Editando categoria: {{$category-> name}}</h3>

       @include('errors._check')
        {!! Form::model ($category,['route'=>['admin.categories.update', $category->id]])!!}

        @include('admin.categories._form')

        <div class="form-group">
            {!! Form::submit('Salvar Categoria',['class'=>'btn btn-primary'])!!}
        </div>

        {!! Form::close() !!}


    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Categorias</h3>
        <br>
            <a href="{{route('admin.categories.create')}}" class="btn btn-default">Nova Categoria</a>
        <br>
        <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
        </thead>
            <tbody>
            @foreach($categories as $category)
            <tr>
                <td>{{$category->id}}</td>
                <td>{{$category->name}}</td>
                <td>
                    <a href="{{route('admin.categories.edit',['id'=>$category->id])}}" class="btn btn-default btn-sm">
                        Editar
                    </a>
                    <a href="{{route('admin.categories.destroy',['id'=>$category->id])}}" class="btn btn-danger btn-sm">
                        Remover
                    </a>
                </td>
            </tr>
            @endforeach
            </tbody>
    </table>
        {!! $categories->render() !!}
    </div>

@endsection